### PR TITLE
Fix an incorrect autocorrect for `Capybara/FindAllFirst` when `find` or `all` with `match: :first` uses a receiver and mark autocorrection as unsafe

### LINKED ISSUE #167: Capybara/FindAllFirst invalid autocorrect
When I enabled Capybara/FindAllFirst and ran autocorrect it changed this view component spec from:

```ruby
link = page.find('tr[data-tree-role="leaf"] a', match: :first, visible: :all)
```

To
```ruby
link = first('tr[data-tree-role="leaf"] a', visible: :all)
```

This caused:
```
     NoMethodError:
       undefined method 'first' for #<RSpec::ExampleGroups::FileComponent::WhenAVersionIdIsSupplied:0x00007f4f6cad9b58>
     # ./spec/components/file_component_spec.rb:46:in 'block (3 levels) in <main>'

```

The component tests are configured like this:
```ruby
  config.include ViewComponent::TestHelpers, type: :component
  config.include ViewComponent::SystemTestHelpers, type: :component
  config.include Capybara::RSpecMatchers, type: :component
```

I was able to fix this by re-adding the `page` variable:
```ruby
link = page.first('tr[data-tree-role="leaf"] a', visible: :all)
```

### PR DESCRIPTION
**Pull request by ydah**
Fixes: https://github.com/rubocop/rubocop-capybara/issues/167

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `main` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Updated documentation.
- [x] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: spec/rubocop/cop/capybara/find_all_first_spec.rb [hunk 1]
```diff
@@ -51,6 +65,20 @@
...
+           ^^^^^^^^^^^^^^^^^^^^^^^ Use `first('a')`.
+      page.all('a', text: 'b', match: :first)
+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use `first('a', text: 'b')`.
+    RUBY
+
+    expect_correction(<<~RUBY)
+      page.first('a')
+      page.first('a', text: 'b')
+    RUBY
+  end
```
Comment (r7kamura) [inline spec/rubocop/cop/capybara/find_all_first_spec.rb]: `page.all` is supposed to return a Capybara::Result which contains multiple elements. But if you autocorrect that to `page.first`, it'll return a Capybara::Node::Element instead, which is just a single element. Wouldn't that break the rest of the program and cause an error?

For example, the code below works fine without any errors,

```ruby
page.all('a', match: :first).each do |link|
  puts link.text
end
```

but if it gets autocorrected like this, it'll start throwing errors

```ruby
page.first('a').each do |link|
  puts link.text
end
```

```
example.rb:...:in '<main>': undefined method 'each' for an instance of Capybara::Node::Element (NoMethodError)

page.first('a').each do |link|
               ^^^^^
```

Comment (r7kamura) [reply spec/rubocop/cop/capybara/find_all_first_spec.rb]: Oh, I see, so this is a built-in issue whether there is a receiver or not. In that case, it looks like we don't really need to deal with it right now.

This cop's inspection and autocorrection are both considered safe, but I really think we should change at least the autocorrection to unsafe.

**Review by r7kamura — APPROVED** [review]
👍 

It's not just about fixing the autocorrection bug; the range of the offensed part has actually changed too. Ideally, the changelog or message should reflect that so we can tell what happened.
